# Specify assignees for pull requests

version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      # Add assignees
      assignees:
          - 'octocat'
          - 'hubot'
