# `dependabot.yml` file using the `dependency-type` option to group updates
# in conjunction with `patterns` and `exclude-patterns`.
# Grouping rules default to applying to version updates only, since
# the `applies-to` key is absent.

version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      groups:
          production-dependencies:
              dependency-type: 'production'
          development-dependencies:
              dependency-type: 'development'
              exclude-patterns:
                  - 'rubocop*'
          rubocop:
              patterns:
                  - 'rubocop*'
