# Using `registries` in conjunction with `insecure-external-code-execution:allow`
# in the same `updates` setting

version: 2
registries:
    ruby-github:
        type: rubygems-server
        url: https://rubygems.pkg.github.com/octocat/github_api
        token: ${{secrets.MY_GITHUB_PERSONAL_TOKEN}}
    dockerhub:
        type: docker-registry
        url: registry.hub.docker.com
        username: octocat
        password: ${{secrets.DOCKERHUB_PASSWORD}}
updates:
    - package-ecosystem: 'bundler'
      directory: '/rubygems-server'
      insecure-external-code-execution: allow
      registries:
          - ruby-github # only access to registries associated with this ecosystem/directory
      schedule:
          interval: 'monthly'
