version: 2
updates:
    - package-ecosystem: docker
      directory: website
      schedule:
          interval: weekly
      groups:
          minorAndPatch:
              update-types:
                  - 'minor'
                  - 'patch'
    - package-ecosystem: docker
      directories:
          - website
          - backend
      schedule:
          interval: weekly
      groups:
          minorAndPatch:
              update-types:
                  - 'minor'
                  - 'patch'
