version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      groups:
          pwa-dependencies:
              applies-to: version-updates
              patterns:
                  - '*'
              update-types:
                  - 'minor'
                  - 'patch'
